// Text_Test.vert
precision mediump float;


struct Circle {
	vec2 center;
	float radius;
};

// #pragma attribute Circle circ;

#define circ _AUTOGENERATED_0001_


#define FLIP_Y


attribute vec2 aTextureCoord;
attribute vec2 aVertexPosition;
attribute float aChar;



// attribute vec2 aTextureCoord, aVertexPosition;
// // attribute vec2 aVertexPosition;
// attribute float aChar;

uniform vec2 uSize;
uniform float uNumChars;
uniform vec2 uOffset;


varying vec2 vTextureCoord;
varying float vChar;


void main(void) {
	Circle circ;
	circ.radius = vChar;
	
	// vec2 vPos = 2.0 * (aVertexPosition / uSize) - vec2(1);
	vec2 vPos = 2.0 * ((aVertexPosition + uOffset) / uSize) - vec2(1);

	// vChar = aChar;
	vChar = circ.radius;

	vTextureCoord = aTextureCoord;

	vTextureCoord.s *= 1.0 / uNumChars;
	vTextureCoord.s += aChar / uNumChars;



	// Circle cc;
	// cc.center.y = vTextureCoord.s;
	// vTextureCoord.s = cc.center.y;




	#ifdef FLIP_Y
	vPos *= vec2(1, -1);
	vTextureCoord = vTextureCoord *  vec2(1, -1) + vec2(0, 1);
	#endif


	gl_Position = vec4(vPos, -1.0, 1.0);
}






